// All user-facing text lives here so localization later only touches this file (spec §4).
export const STR = {
  appName: 'Cascade',
  tagline: 'Clear lines. Let them fall. Chain it.',
  play: 'Play',
  dailyChallenge: 'Daily Challenge',
  highScore: 'Best',
  settings: 'Settings',
  score: 'Score',
  best: 'Best',
  streak: 'Streak',
  pause: 'Pause',
  resume: 'Resume',
  restart: 'Restart',
  home: 'Home',
  gameOver: 'Game Over',
  finalScore: 'Score',
  maxChain: 'Max chain',
  replay: 'Replay',
  share: 'Share',
  shareCopied: 'Copied to clipboard!',
  sound: 'Sound',
  haptics: 'Haptics',
  resetData: 'Reset data',
  resetConfirm: 'Delete ALL progress, scores and streaks? This cannot be undone.',
  resetDone: 'All data reset.',
  on: 'On',
  off: 'Off',
  callouts: {
    nice: 'Nice!',
    great: 'Great!',
    amazing: 'Amazing!',
    unbelievable: 'UNBELIEVABLE!',
    perfect: 'PERFECT!',
  },
  tutorial: {
    step1Title: 'Drag pieces',
    step1Body: 'Drag pieces from the tray onto the 8×8 board.',
    step2Title: 'Fill lines to clear',
    step2Body: 'Complete a full row or column to clear it.',
    step3Title: 'Cascades!',
    step3Body: 'After a clear, blocks fall. New lines formed by the fall clear again — chain it for big points!',
    gotIt: 'Got it!',
    skip: 'Skip',
    next: 'Next',
  },
  daily: {
    title: 'Daily Challenge',
    streakLabel: 'day streak',
    todayBest: "Today's best",
    repairTitle: 'Streak broken!',
    repairOffer: (n: number) => `Repair your 🔥${n} streak — watch a short ad.`,
    repairButton: 'Watch & repair',
    secondTry: 'Second try — watch an ad',
    secondTryHint: 'Best of two scores counts.',
  },
  continueOffer: {
    title: 'Keep going?',
    body: 'Watch to keep going — clears the 2 fullest rows.',
    watch: 'Watch & continue',
    noThanks: 'No thanks',
    free: 'Continue (ad-free)',
  },
  ads: {
    fakeAdTitle: 'Ad placeholder',
    fakeAdBody: 'A real ad would play here.',
    fakeAdSkip: 'Continue',
    removeAds: 'Remove ads forever — $3.99',
    removeAdsShort: 'No ads',
    removeAdsOwned: 'Ads removed ✓',
    restorePurchases: 'Restore purchases',
    restored: 'Purchases restored.',
    nothingToRestore: 'No purchases to restore.',
    purchaseThanks: 'Thank you! Ads are gone forever.',
  },
  share: {
    payload: (score: number, maxChain: number, streak: number) => {
      const parts = [`Cascade 🟦 Score ${score.toLocaleString('en-US')}`, `Max chain ×${maxChain}`];
      if (streak > 0) parts.push(`Day streak 🔥${streak}`);
      return parts.join(' · ');
    },
  },
} as const;
